# Generated by Django 3.2.12 on 2022-02-11 10:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total:')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('Nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Colore',
            fields=[
                ('Nombre', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('Nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Codigo', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10, 'Codigo inválido')])),
                ('Ano', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Año')),
                ('Temporada', models.CharField(choices=[('V', 'Primavera - Verano'), ('I', 'Otoño - Invierno')], max_length=1)),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de Alta:')),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio:')),
                ('Precio_desc', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Precio Descuento:')),
                ('Vendidos', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('S', models.IntegerField()),
                ('M', models.IntegerField()),
                ('L', models.IntegerField()),
                ('XL', models.IntegerField()),
                ('XXL', models.IntegerField()),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Tiendaweb.categoria')),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Tiendaweb.colore')),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Tiendaweb.marca')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Subtotal:')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tiendaweb.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tiendaweb.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Imagene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img1', models.ImageField(default='', upload_to='img_productos/', verbose_name='Imagen Principal:')),
                ('Recorte1', image_cropping.fields.ImageRatioField('Img1', '277x377', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Recorte1')),
                ('Img2', models.ImageField(default='', upload_to='img_productos/', verbose_name='Imagen 2:')),
                ('Recorte2', image_cropping.fields.ImageRatioField('Img2', '277x377', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Recorte2')),
                ('Img3', models.ImageField(default='', upload_to='img_productos/', verbose_name='Imagen 3:')),
                ('Recorte3', image_cropping.fields.ImageRatioField('Img3', '277x377', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Recorte3')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tiendaweb.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tiendaweb.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='itemcarrito',
            constraint=models.UniqueConstraint(fields=('carrito', 'producto'), name='carrito_prod'),
        ),
    ]
