# Generated by Django 3.2.12 on 2022-02-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendaweb', '0002_auto_20220211_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['Vendidos']},
        ),
    ]
