# Generated by Django 3.2.12 on 2022-02-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendaweb', '0003_alter_producto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-Vendidos']},
        ),
    ]
