# Generated by Django 3.2.12 on 2022-02-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendaweb', '0006_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='Cantidad',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
