# Generated by Django 3.2.12 on 2022-02-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendaweb', '0007_categoria_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='colore',
            name='Codigo',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
