# Generated by Django 3.2.12 on 2022-03-14 11:46

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendaweb', '0008_colore_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='Imagen',
            field=models.ImageField(default='', upload_to='img_productos/Categoria/', verbose_name='Imagen:'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='Recorte',
            field=image_cropping.fields.ImageRatioField('Imagen', '277x377', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Recorte'),
        ),
    ]
