# Generated by Django 3.2.12 on 2022-03-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendaweb', '0009_auto_20220314_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='Recorte',
        ),
    ]
