# Generated by Django 3.2.12 on 2022-04-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendaweb', '0010_remove_categoria_recorte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colore',
            options={'ordering': ['Nombre']},
        ),
    ]
