# Generated by Django 3.2.12 on 2022-07-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendaweb', '0014_auto_20220519_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='talle',
            field=models.CharField(default='S', max_length=5),
        ),
    ]
